### ISSUE TITLE
How to not decompose the choose_qparams_affine call_func

### ISSUE THREAD

**Issue by lanluo-nvidia** [pytorch/ao#2456]
Hi,
In the current v0.11.0, after torch.export.export() I have the graph below:
```
(Pdb) print(ep.graph)
graph():
    %linear1_weight : [num_users=1] = get_attr[target=linear1.weight]
    %x : [num_users=2] = placeholder[target=x]
    %choose_qparams_affine : [num_users=2] = call_function[target=torch.ops.torchao.choose_qparams_affine.default](args = (%x, SYMMETRIC, [2, 32], torch.float8_e4m3fn, -448, 448, 1.1920928955078125e-07, torch.float32, None, True, NONE), kwargs = {})
    %getitem : [num_users=2] = call_function[target=operator.getitem](args = (%choose_qparams_affine, 0), kwargs = {})
    %getitem_1 : [num_users=0] = call_function[target=operator.getitem](args = (%choose_qparams_affine, 1), kwargs = {})
    %quantize_affine : [num_users=1] = call_function[target=torch.ops.torchao.quantize_affine.default](args = (%x, [2, 32], %getitem, None, torch.float8_e4m3fn, -448, 448, NONE), kwargs = {})
    %reshape : [num_users=1] = call_function[target=torch.ops.aten.reshape.default](args = (%quantize_affine, [-1, 32]), kwargs = {})
    %numpy_t : [num_users=1] = call_function[target=torch.ops.aten.numpy_T.default](args = (%access_subclass_inner_tensor_default_72,), kwargs = {})
    %_scaled_mm : [num_users=1] = call_function[target=torch.ops.aten._scaled_mm.default](args = (%reshape, %numpy_t, %getitem, %access_subclass_inner_tensor_default_73, None, None, torch.float32, True), kwargs = {})
    %reshape_1 : [num_users=1] = call_function[target=torch.ops.aten.reshape.default](args = (%_scaled_mm, [2, 16]), kwargs = {})
    return (reshape_1,)
```

However if I use the latest torchao nightly, I found that choose_qparams_affine call_func being decomposed to a set of aten ops:
which is probablly introduced by 
https://github.com/pytorch/ao/commit/8940aa72b182afe70f95e33500f01fc270c9f7cd#diff-d2a11602a79e83305208472f1abe6a4106f02ce62a7f9524007181813863fcf6

Is there a way to avoid decompose the choose_qparams_affine call_func?
Or from the decomposed ep.graph, how can I get the undecomposed nodes?

example code:

```
import torch
from torchao.quantization.quant_api import (
    quantize_,
    Float8DynamicActivationFloat8WeightConfig
)

class SimpleNetwork(torch.nn.Module):
    def __init__(self):
        super(SimpleNetwork, self).__init__()
        self.linear = torch.nn.Linear(in_features=32, out_features=16, bias=False)

    def forward(self, x):
        return self.linear(x)

model= SimpleNetwork().eval().cuda()
input = torch.randn(2, 32).cuda()
config = Float8DynamicActivationFloat8WeightConfig()
quantize_(model, config)

ep = torch.export.export(model, (input,), strict=False) 
```

**Comment by angelayi** [comment]
I believe the problem is that there is now a separate choose_qparams_affine for float8, [choose_qparams_affine_float8](https://github.com/pytorch/ao/blob/6dfba041bee0d13bc58acbe1252a27cc83fcaa8f/torchao/quantization/quant_primitives.py#L2181), so it no longer goes through the same [codepath](https://github.com/pytorch/ao/blob/6dfba041bee0d13bc58acbe1252a27cc83fcaa8f/torchao/quantization/quant_primitives.py#L1201) that uses `torch.ops.quant.choose_qparams_affine.default`

**Comment by angelayi** [comment]
cc @jerryzh168 if it's intended that choose_qparams_affine_float8 should become a custom op?

**Comment by lanluo-nvidia** [comment]
Currently after torch.export.export I got the following:
```
(Pdb) print(ep.graph)
graph():
    %p_linear_weight : [num_users=1] = placeholder[target=p_linear_weight]
    %x : [num_users=2] = placeholder[target=x]
    %access_subclass_inner_tensor_default_37 : [num_users=1] = call_function[target=torch.ops.export.access_subclass_inner_tensor.default](args = (%p_linear_weight, original_weight_tensor), kwargs = {})
    %access_subclass_inner_tensor_default_65 : [num_users=2] = call_function[target=torch.ops.export.access_subclass_inner_tensor.default](args = (%access_subclass_inner_tensor_default_37, tensor_impl), kwargs = {})
    %access_subclass_inner_tensor_default_72 : [num_users=1] = call_function[target=torch.ops.export.access_subclass_inner_tensor.default](args = (%access_subclass_inner_tensor_default_65, float8_data), kwargs = {})
    %access_subclass_inner_tensor_default_73 : [num_users=1] = call_function[target=torch.ops.export.access_subclass_inner_tensor.default](args = (%access_subclass_inner_tensor_default_65, scale), kwargs = {})
    %view : [num_users=1] = call_function[target=torch.ops.aten.view.default](args = (%x, [2, 32]), kwargs = {})
    %abs_1 : [num_users=1] = call_function[target=torch.ops.aten.abs.default](args = (%view,), kwargs = {})
    %amax : [num_users=1] = call_function[target=torch.ops.aten.amax.default](args = (%abs_1, [0, 1], True), kwargs = {})
    %div : [num_users=1] = call_function[target=torch.ops.aten.div.Tensor](args = (%amax, 448.0), kwargs = {})
    %reshape : [num_users=1] = call_function[target=torch.ops.aten.reshape.default](args = (%div, [1, 1]), kwargs = {})
    %to : [num_users=2] = call_function[target=torch.ops.aten.to.dtype](args = (%reshape, torch.float32), kwargs = {})
    %quantize_affine_float8 : [num_users=1] = call_function[target=torch.ops.torchao.quantize_affine_float8.default](args = (%x, %to), kwargs = {})
    %reshape_1 : [num_users=1] = call_function[target=torch.ops.aten.reshape.default](args = (%quantize_affine_float8, [-1, 32]), kwargs = {})
    %reshape_2 : [num_users=1] = call_function[target=torch.ops.aten.reshape.default](args = (%to, [1, 1]), kwargs = {})
    %numpy_t : [num_users=1] = call_function[target=torch.ops.aten.numpy_T.default](args = (%access_subclass_inner_tensor_default_72,), kwargs = {})
    %_scaled_mm : [num_users=1] = call_function[target=torch.ops.aten._scaled_mm.default](args = (%reshape_1, %numpy_t, %reshape_2, %access_subclass_inner_tensor_default_73, None, None, torch.float32, True), kwargs = {})
    %reshape_3 : [num_users=1] = call_function[target=torch.ops.aten.reshape.default](args = (%_scaled_mm, [2, 16]), kwargs = {})
    return (reshape_3,)
```
what I can see is that choose_qparams_affine_float8 is decomposed as a set of aten ops, what I want is 
`%choose_qparams_affine_float8 : [num_users=2] = call_function[target=torch.ops.torchao.choose_qparams_affine_float8.default](args = (%x, SYMMETRIC, [2, 32], torch.float8_e4m3fn, -448, 448, 1.1920928955078125e-07, torch.float32, None, True, NONE), kwargs = {})`
    
Is it possible to prevent this op to be decomposed?
This way we can replace this node with our tensorrt implementation.

**Comment by jerryzh168** [comment]
> cc [@jerryzh168](https://github.com/jerryzh168) if it's intended that choose_qparams_affine_float8 should become a custom op?

yeah this can be a custom op if needed. @lanluo-nvidia can you try adding a `register_custom_op` to see if it works?

also I'm a bit unclear on the overall picture here, I haven't tested this personally what does the following look like:
|                 | export | inductor |
| ---------| -------------------| ------| 
| choose_qparams_affine_float8| ? | ? |
| quantize_float8 |  ? | not decompose |
| dequantize_float8 | ? | not decompose|

**Comment by lanluo-nvidia** [comment]
I try to add @_register_custom_op(quant_lib, False)
on https://github.com/pytorch/ao/blob/main/torchao/quantization/quant_primitives.py#L2181
and I got the following error
`RuntimeError: Tried to register an operator (torchao::quantize_affine(Tensor input, SymInt[] block_size, Tensor scale, Tensor? zero_point, ScalarType output_dtype, Scalar? quant_min=None, Scalar? quant_max=None) -> Tensor) with the same name and overload name multiple times. Each overload's schema should only be registered with a single call to def(). Duplicate registration: registered at /dev/null:228. Original registration: registered at /dev/null:228`

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=en-US style='font-family:Calibri;font-size:11.0pt'>


<div style='direction:ltr'>


  | export
-- | --
choose_qparams_affine_float8 | please do not   decompose
quantize_float8 | this is not   decomposed (good)
dequantize_float8 | this is not   decomposed (good)



</div>

<p style='margin:0in;font-family:Calibri;font-size:11.0pt'>&nbsp;</p>


</body>

</html>

**Comment by angelayi** [comment]
@lanluo-nvidia I think you want to do something like https://github.com/pytorch/ao/pull/2461

**Comment by lanluo-nvidia** [comment]
@angelayi  yes, this is what i want.
@jerryzh168  I tried with @angelayi 's branch it is working.
Same for Int8DynamicActivationInt8WeightConfig
I can see choose_qparams_affine is not decomposed after export which is good,
but quantize/dquantize is decomposed, please also do not decompose these two in torch exported graph.

**Comment by angelayi** [comment]
What do you mean by quantize/dequantize are decomposed?
The graph looks like:
```
ExportedProgram:
    class GraphModule(torch.nn.Module):
        def forward(self, p_linear_weight: "f32[16, 32]", x: "f32[2, 32]"):
            # No stacktrace found for following nodes
            access_subclass_inner_tensor_default_37: "f32[16, 32]" = torch.ops.export.access_subclass_inner_tensor.default(p_linear_weight, 'original_weight_tensor');  p_linear_weight = None
            access_subclass_inner_tensor_default_65: "f8e4m3fn[16, 32]" = torch.ops.export.access_subclass_inner_tensor.default(access_subclass_inner_tensor_default_37, 'tensor_impl');  access_subclass_inner_tensor_default_37 = None
            access_subclass_inner_tensor_default_72: "f8e4m3fn[16, 32]" = torch.ops.export.access_subclass_inner_tensor.default(access_subclass_inner_tensor_default_65, 'float8_data')
            access_subclass_inner_tensor_default_73: "f32[1, 1]" = torch.ops.export.access_subclass_inner_tensor.default(access_subclass_inner_tensor_default_65, 'scale');  access_subclass_inner_tensor_default_65 = None

             # File: /data/users/angelayi/pytorch/torch/nn/modules/linear.py:125 in forward, code: return F.linear(input, self.weight, self.bias)
            choose_qparams_affine_float8: "f32[1, 1]" = torch.ops.torchao.choose_qparams_affine_float8.default(x, [2, 32])
            quantize_affine_float8: "f8e4m3fn[2, 32]" = torch.ops.torchao.quantize_affine_float8.default(x, choose_qparams_affine_float8);  x = None
            reshape: "f8e4m3fn[2, 32]" = torch.ops.aten.reshape.default(quantize_affine_float8, [-1, 32]);  quantize_affine_float8 = None
            reshape_1: "f32[1, 1]" = torch.ops.aten.reshape.default(choose_qparams_affine_float8, [1, 1]);  choose_qparams_affine_float8 = None
            numpy_t: "f8e4m3fn[32, 16]" = torch.ops.aten.numpy_T.default(access_subclass_inner_tensor_default_72);  access_subclass_inner_tensor_default_72 = None
            _scaled_mm: "f32[2, 16]" = torch.ops.aten._scaled_mm.default(reshape, numpy_t, reshape_1, access_subclass_inner_tensor_default_73, None, None, torch.float32, True);  reshape = numpy_t = reshape_1 = access_subclass_inner_tensor_default_73 = None
            reshape_2: "f32[2, 16]" = torch.ops.aten.reshape.default(_scaled_mm, [2, 16]);  _scaled_mm = None
            return (reshape_2,)
```

which seems to be equivalent to what you had previously?
